### ISSUE TITLE
eb.close() hangs for about 1 minute

### ISSUE THREAD

**Issue by gaol** [rc-dukes/vertx-eventbus-python#13]
### Reproduce Steps

- Server Side

> cd java
> mvn clean install -DcreateAssembly=true
> java -jar target/python-eventbus-example-3.8.5-jar-with-dependencies.jar -p 7000

- Client side

In Python 3.7 console:

> pip install -i https://test.pypi.org/simple/ vertx-eventbus-python==3.8.5a8

	>>> from Vertx.eventbus import Eventbus
	>>> eb = Eventbus()
	>>> eb.state
	<State.OPEN: 1>
	>>> body={'msg':'hi'}
	>>> eb.send('echo',body)
	>>> eb.close()   ## HERE it hangs about 1 minute
	>>> eb.state
	<State.CLOSED: 3>
	>>> eb.open()    ## HERE eb.open() failed, may needs a new sokcet?
	Traceback (most recent call last):
	  File "/home/lgao/anaconda3/lib/python3.7/site-packages/Vertx/eventbus.py", line 226, in open
	    self._connect()
	  File "/home/lgao/anaconda3/lib/python3.7/site-packages/Vertx/eventbus.py", line 238, in _connect
	    self.sock.connect((self.host, self.port))
	OSError: [Errno 9] Bad file descriptor

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	  File "/home/lgao/anaconda3/lib/python3.7/site-packages/Vertx/eventbus.py", line 230, in open
	    self.close()
	  File "/home/lgao/anaconda3/lib/python3.7/site-packages/Vertx/eventbus.py", line 406, in close
	    self.wait(State.CLOSED,timeOut=self.timeOut)
	  File "/home/lgao/anaconda3/lib/python3.7/site-packages/Vertx/eventbus.py", line 258, in wait
	    raise Exception("wait for %s timedOut after %.3f secs" % (state.name,timeOut))
	Exception: wait for CLOSED timedOut after 60.000 secs

The `eb.close()` hangs for about 1 minute, and `eb.open()` afterwards throws above exception.

**Comment by WolfgangFahl** [comment]
@gaol thank you for reporting his
I'll have to try this out and get back to you
